// src/routes/+page.svelte
<script lang="ts">
  import SongList from "$lib/components/song-list.svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { songListCtx, type Song } from "$lib/songs.svelte";
  import { resource } from "runed";
  import type { PageProps } from "./$types";
  import { devicesResourceCtx } from "$lib/devices.svelte";
  import DeviceSelector from "$lib/components/device-selector.svelte";
  import StatusButtons from "$lib/components/status-buttons.svelte";
  import SongAdder from "$lib/components/song-adder/index.js";

  let { data }: PageProps = $props();

  const songListResource = resource(
    () => [],
    async () => {
      return await invoke<Song[]>("list_songs");
    },
    {
      initialValue: data.initialSongs,
    }
  );

  const devicesResource = resource(
    () => [],
    async () => {
      return await invoke<string[]>("list_audio_devices");
    },
    {
      initialValue: data.initialDevices,
    }
  );

  devicesResourceCtx.set(devicesResource);
  songListCtx.set(songListResource);
</script>

<p>hi, home page will soon be finished</p>

<SongAdder />
<DeviceSelector />
<SongList />
<br />
<StatusButtons />
<br />

// src/routes/index.tsx
import { SongList } from "@/components/song-list";
import { StatusButtons } from "@/components/status-buttons";
import { SongAdder } from "@/components/song-adder";
import { DeviceSelector } from "@/components/device-selector";

export function HomePage() {
  return (
    <>
      <SongAdder />
      <DeviceSelector />
      <SongList />
      <br />
      <StatusButtons />
    </>
  );
}
